services:
  private-gpt:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    ports:
      - 80:80
    environment:
      PORT: 80
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
